spring:
  application:
    name: boardVer3     #    프로젝트 명
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board2024_v3    # 데이터 베이스 이름
    username: root
    password: green502
mybatis:
  mapper-locations: mappers/**/*.xml      # resources 아래에 xml 담긴 (mappers) 폴더이름

springdoc:
  swagger-ui:
    path: /swagger
